"team_name": "AGEPT" # Your team name
"eval_method": ["mcqa", 'quantiz'] # mcqa, reward, rag, quantiz
"task_type": "causal_lm" # causal_lm, seq2seq
"policy_model_path": "BaptisteL/m3-best-model" # Your path to the final checkpoint
"reference_model_path": "BaptisteL/m2-reference-model" # The repo id of your pretrained reference model
"quantized_policy_model_path": "BaptisteL/m3-best-model" # Your path to the final quantized checkpoint
"rag_policy_model_path": "none" # Your path to the final RAG checkpoint
"test_data_path": "data/m3_epfl-4answers_validation.jsonl" # Your path to the test data
"dpo_model_args":
"rag_model_args": # Put any model arguments required to load your rag model below
  "encoder_model_path": "none"
  "retriever_model_path": "none"
  "document_dir": "none"
"quantized_model_args":
  "load_in_4bit": True
